export const MAGIC_WORDS_CONFIG = {
  scene: {
    titleFontSize: 24,
    statusFontSize: 15,
    titleTop: 18,
    titleAnchorX: 0.5,
    backButtonWidth: 120,
    backButtonX: 16,
    backButtonY: 48,
    contentX: 16,
    contentY: 104,
    contentHorizontalPadding: 32,
    contentBottomPadding: 16,
    minContentWidth: 240,
    minContentHeight: 200,
    statusOffsetY: 8,
  },
  panel: {
    nameFontSize: 20,
    textFontSize: 28,
    fallbackEmojiFontSize: 28,
    avatarSize: 48,
    outerPad: 10,
    bubblePad: 10,
    bubbleMaxWidth: 560,
    bubbleWidthSafetyPadding: 14,
    contentTopPad: 8,
    rowGap: 10,
    contentBottomPad: 8,
  },
  message: {
    bubbleCornerRadius: 12,
    bubbleGapY: 6,
    lineHeight: 36,
    emojiSize: 30,
    emojiGapX: 2,
    minTextWidth: 1,
    leftBubbleColor: 0x1f274f,
    rightBubbleColor: 0x2e387d,
  },
  scroll: {
    defaultViewportWidth: 320,
    defaultViewportHeight: 320,
    minViewport: 1,
    maskCornerRadius: 12,
    maskColor: 0x000000,
    scrollBarWidthOffset: 10,
    scrollBarTopOffset: 6,
    scrollBarVerticalPadding: 12,
  },
} as const;
