export const PHOENIX_FLAME_CONFIG = {
  maxParticles: 10,
  spawnIntervalMs: 55,
  sparkChance: 0.3,
  spawnOffset: {
    x: [-24, 24] as [number, number],
    y: [-12, 12] as [number, number],
  },
  spawn: {
    spark: {
      lifeMs: [350, 700] as [number, number],
      vx: [-110, 110] as [number, number],
      vy: [-360, -250] as [number, number],
      startSize: [7, 12] as [number, number],
      endSize: [1.5, 4] as [number, number],
    },
    flame: {
      lifeMs: [520, 980] as [number, number],
      vx: [-55, 55] as [number, number],
      vy: [-300, -190] as [number, number],
      startSize: [16, 30] as [number, number],
      endSize: [4, 10] as [number, number],
    },
    spin: [-8, 8] as [number, number],
    rotation: [-0.5, 0.5] as [number, number],
  },
  render: {
    initialZ: 1000,
    initialTint: 0xfff1a8,
    initialAlpha: 1,
    zRange: 100,
    colorStops: [
      { maxT: 0.2, color: 0xfff1a8 },
      { maxT: 0.5, color: 0xffb347 },
      { maxT: 0.8, color: 0xff6d2d },
      { maxT: 1.0, color: 0x8f1f00 },
    ] as Array<{ maxT: number; color: number }>,
  },
  particleDefaults: {
    active: false,
    spark: false,
    x: 0,
    y: 0,
    rotation: 0,
    width: 0,
    height: 0,
    alpha: 0,
    tint: 0xff6d2d,
    z: 0,
    ageMs: 0,
    lifeMs: 1000,
    vx: 0,
    vy: 0,
    startSize: 16,
    endSize: 6,
    spin: 0,
  },
  update: {
    sparkChaos: 210,
    flameChaos: 120,
    sparkDrag: 0.9,
    flameDrag: 0.94,
    sparkLift: 18,
    flameLift: 10,
    frameMs: 16.6667,
    sparkHeightScale: 1.1,
    flameHeightScale: 1.8,
    alpha: {
      sparkFadeIn: 12,
      flameFadeIn: 8,
      sparkFadeOut: 1.3,
      flameFadeOut: 1,
    },
  },
} as const;
