export const ACE_OF_SHADOWS_CONFIG = {
  scene: {
    titleFontSize: 24,
    titleTop: 18,
    titleAnchorX: 0.5,
    backButtonWidth: 120,
    backButtonX: 16,
    backButtonY: 56,
  },
  gameplay: {
    totalCards: 144,
    stackCount: 4,
    moveIntervalMs: 1000,
    moveDurationMs: 2000,
    zCounterStart: 1,
  },
  layout: {
    cardWidthInitial: 90,
    cardHeightInitial: 126,
    minCardWidth: 54,
    maxCardWidth: 120,
    cardWidthDivisor: 7,
    cardAspectRatio: 1.4,
    stackOffsetY: 2,
    minViewportSize: 320,
    minHorizontalPadding: 50,
    sidePaddingCardWidthFactor: 0.65,
    stackTopPadding: 120,
    movingCardZBase: 100000,
    stackZStride: 1000,
  },
  easing: {
    midpoint: 0.5,
    powerFactor: 2,
  },
  tint: {
    hueStep: 17,
    hueCircle: 360,
    hueSectorSize: 60,
    threshold1: 60,
    threshold2: 120,
    threshold3: 180,
    threshold4: 240,
    threshold5: 300,
    chroma: 0.45,
    match: 0.2,
    channelScale: 255,
    redShift: 16,
    greenShift: 8,
  },
  cardLabel: {
    ranks: ["2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"],
    fontSize: 18,
    fontWeight: "700",
    fill: "#ffffff",
    strokeColor: "#0b1020",
    strokeWidth: 3,
    minPadding: 4,
    paddingFactor: 0.08,
    baseWidth: 90,
    minScale: 0.75,
  },
} as const;
